language: node_js
node_js:
    - "6"
    - "8"
    - "10"
dist: trusty # needs Ubuntu Trusty
sudo: required
addons:
  chrome: stable # have Travis install chrome stable.
cache:
  npm: true
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
